In [1]:
import numpy as np
import datetime

## list vs. nparray

In [2]:
#list
li = list(range(1,10000000))
startTime = datetime.datetime.now()

for i in li :
    i*10

print('List execution time :',datetime.datetime.now()-startTime)

#nparray
ar = np.arange(1,10000000)
startTime = datetime.datetime.now()

ar*10

print('ndarray execution time :',datetime.datetime.now()-startTime)

List execution time : 0:00:00.718615
ndarray execution time : 0:00:00.015600


## array

In [7]:
ar = np.arange(25) #0-24
print(ar, '\n')

#5*5 행렬 변환
ar = ar.reshape(5,5)
print(ar, '\n')

#to diagonal matrix
#[0,0]을 기준으로 대각선 데이터만 가져와서 생성
# k : [0,k] 값의 대각선 방향으로 생성
print(np.diag(ar), '\n')
print(np.diag(ar, k=1), '\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[ 0  6 12 18 24] 

[ 1  7 13 19] 



## 난수생성

In [41]:


print(np.random.normal(size =3), "\n") #size = #random_num
print(np.random.normal(size =(3,3)))

#seed : 난수표 번호 
#seed를 맞추면 계속 동일한 난수 발생
for i in range(3):
    np.random.seed(seed =5)
    print(np.random.normal(size =3)) 
    
#0과 1을 추출 1의 확률을 0.3으로 10번 추출
# N : trials
# p : prob.
print(np.random.binomial(n=1, p=0.5, size=10))
print(np.random.binomial(n=10, p=0.5, size=10))

[-0.25209213  0.74572695  0.77690759] 

[[ 1.01842113  1.06135144 -0.71046645]
 [-0.2151878  -0.76076031 -0.71116323]
 [ 1.14150774 -0.50175555 -0.07915136]]
[ 0.44122749 -0.33087015  2.43077119]
[ 0.44122749 -0.33087015  2.43077119]
[ 0.44122749 -0.33087015  2.43077119]
[1 1 0 0 0 1 0 0 1 0]
[5 4 6 5 5 4 4 4 4 3]


## 행렬연산

In [44]:
li1 = [1,2,3]
li2 = [4,5,6]

print(li1+li2) #리스트 결합

ar1 = np.array(li1)
ar2 = np.array(li2)

print(ar1+ar2) #nparray는 same shape일 경우, 산술연산

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [57]:
ar = np.arange(1,13).reshape(4,3)
print('original \n' ,ar)
print('\n첫 행  : \n' ,ar[0])
print('\n0-3행  : \n' ,ar[0:3])
print('\n1행1열 : \n' ,ar[1,1])
print('\n0,3행  : \n', ar[[0,3]]) #0, 3행출력

original 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

첫 행  : 
 [1 2 3]

0-3행  : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

1행1열 : 
 5

0,3행  : 
 [[ 1  2  3]
 [10 11 12]]


In [67]:
ar = np.arange(100,500,100).reshape(2,2)

ar= np.array([[2,3],[2,10]])

print(ar)
print(np.prod(ar, axis=0)) #[4, 30]
print(np.prod(ar, axis=1)) #[6, 20]

print(np.matmul(ar,ar))

[[ 2  3]
 [ 2 10]]
[ 4 30]
[ 6 20]
[[ 10  36]
 [ 24 106]]


In [73]:
k = [[1,2],[3,4]]
l = [[5,6],[7,8]]

print(np.concatenate((k,l), axis=0))

print(np.concatenate((k,l), axis=1))

print(np.split(k,(1,1), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[array([[1],
       [3]]), array([], shape=(2, 0), dtype=int32), array([[2],
       [4]])]


In [84]:
m = np.arange(16).reshape(4,4)
print(m, '\n')
m_split = np.split(m, [2,3], axis =0)
#[2,3] 자르는 자리 --> 즉, 1,2번째 열 / 3번째 열 / 나머지 열 이렇게 split 됨!

for i in range(len(m_split)):
    print( m_split[i])
    
    

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

0 [[0 1 2 3]
 [4 5 6 7]]
1 [[ 8  9 10 11]]
2 [[12 13 14 15]]
